/**
 * Build-time CSS custom-property generator (Theme_Controller, task 3.1).
 *
 * Emits one `:root[data-palette][data-theme]` selector block for every
 * (palette × resolved mode) pair — four palettes × {dark, light} = eight
 * blocks — declaring `--color-*` custom properties. Every property name is
 * derived from the flat variant keys returned by {@link resolveVariant}
 * (e.g. `text-primary` → `--color-text-primary`) and every value is read from
 * `token.value`. No color literal is hardcoded in this module; all values
 * originate in the Token_System (Requirements 3.2, 4.7, 4.10, 4.11, 25.3).
 *
 * Switching theme/palette at runtime is then a matter of flipping the
 * `data-palette` / `data-theme` attributes on `<html>` (task 3.3); the matching
 * `:root[...]` block applies its variables with zero re-render and no flash.
 *
 * {@link generatePaletteCss} is the pure, deterministic core: given the fixed
 * palette/mode sets and the token sources, it always returns the same string.
 * A thin build step (or test harness) writes its output to a `.css` asset.
 */

import { THEME_PALETTES, THEME_DATA_ATTRIBUTES } from "@/constants";
import type { ResolvedMode, ThemePalette } from "@/types";
import { resolveVariant } from "./resolve";

/**
 * The two resolved modes each palette variant is emitted for. `data-theme`
 * carries the resolved mode, so dark mode selects the palette's dark variant
 * and light mode its light variant (Requirement 4.10).
 */
const RESOLVED_MODES: readonly ResolvedMode[] = ["dark", "light"] as const;

/**
 * Prefix shared by every generated color custom property
 * (e.g. `--color-text-primary`).
 */
export const COLOR_CSS_VAR_PREFIX = "--color-";

/** Header comment prepended to the generated stylesheet. */
const GENERATED_FILE_HEADER =
  "/* AUTO-GENERATED by src/services/theme/css-generator.ts — do not edit by hand. */";

/**
 * Converts a variant key to a stable kebab-case CSS segment. Already-kebab
 * keys (`text-primary`) pass through unchanged; camelCase keys (`deepSpace`)
 * become `deep-space`. Mirrors the kebab convention used in `resolve.ts`.
 */
function toKebabCase(key: string): string {
  return key.replace(/([A-Z])/g, "-$1").toLowerCase();
}

/**
 * Derives the `--color-*` custom-property name for a {@link resolveVariant}
 * key (Requirement 4.7).
 */
export function colorVarName(key: string): string {
  return `${COLOR_CSS_VAR_PREFIX}${toKebabCase(key)}`;
}

/**
 * Builds the attribute selector for a (palette, resolved mode) pair using the
 * shared {@link THEME_DATA_ATTRIBUTES} table so the generator and the runtime
 * theme script agree on attribute names.
 */
export function paletteSelector(
  palette: ThemePalette,
  mode: ResolvedMode,
): string {
  const { palette: paletteAttr, theme: themeAttr } = THEME_DATA_ATTRIBUTES;
  return `:root[${paletteAttr}="${palette}"][${themeAttr}="${mode}"]`;
}

/**
 * Builds a single selector block for one palette + resolved mode. Declarations
 * are sorted by property name for deterministic, diff-friendly output.
 */
function generateBlock(palette: ThemePalette, mode: ResolvedMode): string {
  const variant = resolveVariant(palette, mode);
  const declarations = Object.entries(variant)
    .map(([key, tok]) => `  ${colorVarName(key)}: ${tok.value};`)
    .sort()
    .join("\n");
  return `${paletteSelector(palette, mode)} {\n${declarations}\n}`;
}

/**
 * Generates the complete palette stylesheet: eight `:root[...]` blocks covering
 * all four palettes across dark and light, each exposing the active palette's
 * token values as `--color-*` custom properties.
 *
 * Pure and deterministic — no DOM, no I/O — so it is safe to call at build time
 * and straightforward to test.
 */
export function generatePaletteCss(): string {
  const blocks: string[] = [];
  for (const palette of THEME_PALETTES) {
    for (const mode of RESOLVED_MODES) {
      blocks.push(generateBlock(palette, mode));
    }
  }
  return `${GENERATED_FILE_HEADER}\n\n${blocks.join("\n\n")}\n`;
}
