// Feature: next-gen-portfolio-platform, Property 44: Every animated asset is named or marked decorative
//
// Validates: Requirements 25.7
//
// Property 44: Every animated asset is named or marked decorative.
// For any rendered AssetPlayer, the container either exposes a non-empty
// accessible name (aria-label) or marks the asset as decorative
// (aria-hidden="true"). When neither is provided, neither attribute is set
// (the component renders without explicit a11y attrs — documented behavior).
//
// Contract under test (`@/components/shared/AssetPlayer`):
//   AssetPlayer({ src, name?, decorative?, trigger?, width?, height? })
//     - When `name` is a non-empty string and `decorative` is false/absent:
//         container has aria-label === name AND role === "img"
//     - When `decorative` is true:
//         container has aria-hidden === "true"
//         (regardless of whether `name` is also provided)
//     - When neither `name` nor `decorative` is provided:
//         container has neither aria-label nor aria-hidden
//
// KEY PROPERTY: for any render where name is non-empty OR decorative is true,
// the correct a11y attribute is set on the container.
//
// Strategy:
//   Three scenario shapes generated by fast-check:
//   (a) NAMED: non-empty name + decorative=false → aria-label equals name, role="img"
//   (b) DECORATIVE: decorative=true (name may or may not be present) → aria-hidden="true"
//   (c) NEITHER: no name, decorative=false → no aria-label, no aria-hidden
//
//   Mocks:
//   - `@lottiefiles/dotlottie-react` → renders a simple <div data-testid="mock-dotlottie" />
//   - `@/hooks` (useReducedMotion, useTheme) → stable stubs
//   - `@/services/theme` (resolveVariant) → returns empty record
//   - `@/components/shared/AssetPlayer/AssetPlayer.style` → returns empty style objects
//
// Tooling: Vitest + fast-check, numRuns = 100.

import { describe, expect, it, vi, beforeAll } from "vitest";
import * as fc from "fast-check";
import { render } from "@testing-library/react";
import React from "react";

// ---------------------------------------------------------------------------
// Module mocks — must be declared before the component is imported.
// ---------------------------------------------------------------------------

// Mock @lottiefiles/dotlottie-react so no real dotLottie loading occurs.
vi.mock("@lottiefiles/dotlottie-react", () => ({
  DotLottieReact: (props: Record<string, unknown>) =>
    React.createElement("div", { "data-testid": "mock-dotlottie" }),
}));

// Mock the hooks used by AssetPlayer.
vi.mock("@/hooks", () => ({
  useReducedMotion: () => false,
  useTheme: () => ({
    palette: "aurora",
    resolved: "dark",
    mode: "dark",
    setMode: vi.fn(),
    setPalette: vi.fn(),
  }),
}));

// Mock the theme service so resolveVariant returns an empty record.
vi.mock("@/services/theme", () => ({
  resolveVariant: () => ({}),
}));

// Mock the style module so no token imports are needed at test time.
vi.mock("@/components/shared/AssetPlayer/AssetPlayer.style", () => ({
  getAssetPlayerStyles: () => ({}),
  fallbackStyles: {},
  staticFrameStyles: {},
}));

// ---------------------------------------------------------------------------
// Import the component AFTER mocks are registered.
// ---------------------------------------------------------------------------
import { AssetPlayer } from "@/components/shared/AssetPlayer/AssetPlayer";

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** Non-empty string suitable for an accessible name. */
const nonEmptyNameArb = fc
  .string({ minLength: 1, maxLength: 80 })
  .filter((s) => s.trim().length > 0);

/** A valid src URL (just needs to be a non-empty string for the mock). */
const srcArb = fc.constant("https://example.com/animation.lottie");

/** Optional trigger value. */
const triggerArb = fc.oneof(
  fc.constant("auto" as const),
  fc.constant("hover" as const),
  fc.constant("visible" as const),
);

/** Optional width/height values. */
const dimensionArb = fc.oneof(
  fc.constant("100%" as string | number),
  fc.integer({ min: 50, max: 800 }),
);

// ---------------------------------------------------------------------------
// Scenario shapes
// ---------------------------------------------------------------------------

type NamedScenario = {
  kind: "named";
  src: string;
  name: string;
  trigger: "auto" | "hover" | "visible";
  width: string | number;
  height: string | number;
};

type DecorativeScenario = {
  kind: "decorative";
  src: string;
  name: string | undefined;
  trigger: "auto" | "hover" | "visible";
  width: string | number;
  height: string | number;
};

type NeitherScenario = {
  kind: "neither";
  src: string;
  trigger: "auto" | "hover" | "visible";
  width: string | number;
  height: string | number;
};

type Scenario = NamedScenario | DecorativeScenario | NeitherScenario;

/** (a) NAMED: non-empty name, decorative=false */
const namedArb: fc.Arbitrary<NamedScenario> = fc
  .record({
    src: srcArb,
    name: nonEmptyNameArb,
    trigger: triggerArb,
    width: dimensionArb,
    height: dimensionArb,
  })
  .map((r) => ({ kind: "named", ...r }));

/** (b) DECORATIVE: decorative=true, name may or may not be present */
const decorativeArb: fc.Arbitrary<DecorativeScenario> = fc
  .record({
    src: srcArb,
    name: fc.oneof(fc.constant(undefined), nonEmptyNameArb),
    trigger: triggerArb,
    width: dimensionArb,
    height: dimensionArb,
  })
  .map((r) => ({ kind: "decorative", ...r }));

/** (c) NEITHER: no name, decorative=false */
const neitherArb: fc.Arbitrary<NeitherScenario> = fc
  .record({
    src: srcArb,
    trigger: triggerArb,
    width: dimensionArb,
    height: dimensionArb,
  })
  .map((r) => ({ kind: "neither", ...r }));

/** Discriminated arbitrary over all three scenario shapes. */
const scenarioArb: fc.Arbitrary<Scenario> = fc.oneof(
  namedArb,
  decorativeArb,
  neitherArb,
);

// ---------------------------------------------------------------------------
// Helper: render and return the outermost container div
// ---------------------------------------------------------------------------

function renderAssetPlayer(scenario: Scenario): HTMLElement {
  let element: React.ReactElement;

  switch (scenario.kind) {
    case "named":
      element = React.createElement(AssetPlayer, {
        src: scenario.src,
        name: scenario.name,
        decorative: false,
        trigger: scenario.trigger,
        width: scenario.width,
        height: scenario.height,
      });
      break;
    case "decorative":
      element = React.createElement(AssetPlayer, {
        src: scenario.src,
        name: scenario.name,
        decorative: true,
        trigger: scenario.trigger,
        width: scenario.width,
        height: scenario.height,
      });
      break;
    case "neither":
      element = React.createElement(AssetPlayer, {
        src: scenario.src,
        trigger: scenario.trigger,
        width: scenario.width,
        height: scenario.height,
      });
      break;
  }

  const { container } = render(element);
  // The outermost element rendered by AssetPlayer is always a <div>.
  const div = container.firstElementChild as HTMLElement;
  return div;
}

// ---------------------------------------------------------------------------
// Property test
// ---------------------------------------------------------------------------

describe("Property 44: Every animated asset is named or marked decorative", () => {
  it("sets aria-label when name is provided, aria-hidden when decorative, neither when neither", () => {
    fc.assert(
      fc.property(scenarioArb, (scenario) => {
        const container = renderAssetPlayer(scenario);

        switch (scenario.kind) {
          case "named": {
            // aria-label must equal the provided name, role must be "img".
            expect(container.getAttribute("aria-label")).toBe(scenario.name);
            expect(container.getAttribute("role")).toBe("img");
            // Must NOT be hidden from assistive technology.
            expect(container.getAttribute("aria-hidden")).toBeNull();
            break;
          }
          case "decorative": {
            // aria-hidden must be "true" — asset is decorative.
            expect(container.getAttribute("aria-hidden")).toBe("true");
            // aria-label must NOT be set (decorative takes precedence).
            expect(container.getAttribute("aria-label")).toBeNull();
            break;
          }
          case "neither": {
            // Neither attribute should be present — documented behavior.
            expect(container.getAttribute("aria-label")).toBeNull();
            expect(container.getAttribute("aria-hidden")).toBeNull();
            break;
          }
        }
      }),
      { numRuns: 100 },
    );
  });

  it("KEY PROPERTY: any render with non-empty name OR decorative=true has the correct a11y attribute", () => {
    // This property focuses on the core guarantee: if the caller provides
    // accessibility information (a name or a decorative flag), the component
    // always surfaces it correctly on the container element.
    const namedOrDecorativeArb: fc.Arbitrary<
      NamedScenario | DecorativeScenario
    > = fc.oneof(namedArb, decorativeArb);

    fc.assert(
      fc.property(namedOrDecorativeArb, (scenario) => {
        const container = renderAssetPlayer(scenario);

        if (scenario.kind === "named") {
          // Non-empty name → aria-label is set and non-empty.
          const label = container.getAttribute("aria-label");
          expect(label).not.toBeNull();
          expect(label!.length).toBeGreaterThan(0);
          expect(label).toBe(scenario.name);
        } else {
          // decorative=true → aria-hidden="true" is set.
          expect(container.getAttribute("aria-hidden")).toBe("true");
        }
      }),
      { numRuns: 100 },
    );
  });
});
